document.writeln("    	<ul>");
document.writeln("        	<li class=\"l1\" style=\"margin-bottom:5px;\">");
document.writeln("        		<dl>");
document.writeln("                	<dt>呼吸<br/>系统</dt>");
document.writeln("                    <dd>");
document.writeln("                    	<a href=\"/hxxt_fa/\" title=\"肺癌\" style='color:#ff0000;'>肺癌</a> | ");
document.writeln("                        <a href=\"/hxxt_bya/\" title=\"鼻咽癌\">鼻咽癌</a><br/>");
document.writeln("                        <a href=\"/hxxt_ha/\" title=\"喉癌\">喉癌</a> | ");
document.writeln("                        <a href=\"/hxxt_qgl/\" title=\"气管癌\">气管癌</a>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("            <li class=\"l2\" style=\"margin-bottom:5px;\">");
document.writeln("        		<dl>");
document.writeln("                	<dt>消化<br/>系统</dt>");
document.writeln("                    <dd>");
document.writeln("                        <a href=\"/xhxt_wa/\" title=\"胃癌\">胃癌</a>｜");
document.writeln("                        <a href=\"/xhxt_ga/\" title=\"肝癌\" style='color:#ff0000;'>肝癌</a>｜");
document.writeln("                        <a href=\"/xhxt_sga/\" title=\"食道癌\">食道癌</a>｜");
document.writeln("                        <a href=\"/xhxt_jca/\" title=\"结肠癌\" style='color:#ff0000;'>结肠癌</a>｜");
document.writeln("                        <a href=\"/xhxt_zca/\" title=\"直肠癌\" style='color:#ff0000;'>直肠癌</a><br/>");
document.writeln("                        <a href=\"/nfm_yxa/\" title=\"胰腺癌\">胰腺癌</a>｜");
document.writeln("                        <a href=\"/xhxt_kqa/\" title=\"口腔癌\">口腔癌</a>｜");
document.writeln("                        <a href=\"/xhxt_sa/\" title=\"舌癌\">舌癌</a>｜");
document.writeln("                        <a href=\"/xhxt_dga/\" title=\"胆管癌\">胆管癌</a>｜");
document.writeln("                        <a href=\"/xhxt_dna/\" title=\"胆囊癌\">胆囊癌</a>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("            <li class=\"l3\" style=\"margin-bottom:5px;\">");
document.writeln("        		<dl>");
document.writeln("                	<dt>妇科<br/>肿瘤</dt>");
document.writeln("                    <dd>");
document.writeln("                        <a href=\"/fk_rxa/\" title=\"乳腺癌\">乳腺癌</a>｜");
document.writeln("                        <a href=\"/fk_gja/\" title=\"宫颈癌\">宫颈癌</a>｜");
document.writeln("                        <a href=\"/fk_lca/\" title=\"卵巢癌\">卵巢癌</a><br/>");
document.writeln("                        <a href=\"/fk_zgnma/\" title=\"子宫癌\">子宫癌</a>｜");
document.writeln("                        <a href=\"/fk_wya/\" title=\"外阴癌\">外阴癌</a>｜");
document.writeln("                        <a href=\"/fk_yda/\" title=\"阴道癌\">阴道癌</a>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("            <li class=\"l4\" style=\"margin-bottom:5px;\">");
document.writeln("        		<dl>");
document.writeln("                	<dt>泌尿<br/>系统</dt>");
document.writeln("                    <dd>");
document.writeln("                        <a href=\"/mnxt_sa/\" title=\"肾癌\" style='color:#ff0000;'>肾癌</a>｜");
document.writeln("                        <a href=\"/mnxt_pga/\" title=\"膀胱癌\">膀胱癌</a><br/>");
document.writeln("                        <a href=\"/mnxt_sng/\" title=\"输尿管肿瘤\">输尿管肿瘤</a>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("            <li style=\"clear:both; height:1px; overflow:hidden; width:100%; margin:0; padding:0; border-bottom:1px dashed #ccc; margin-bottom:7px;\"></li>");
document.writeln("            <li class=\"l1\">");
document.writeln("        		<dl>");
document.writeln("                	<dt>内分泌<br/>系统</dt>");
document.writeln("                    <dd>");
document.writeln("                        <a href=\"/nfm_jzxa/\" title=\"甲状腺癌\">甲状腺癌</a> ｜");
document.writeln("                        <a href=\"/mnxt_qlxa/\" title=\"前列腺癌\">前列腺癌</a><br/>");
document.writeln("                        <a href=\"/nfm_ctl/\" title=\"恶性垂体瘤\">恶性垂体瘤</a> ｜");
document.writeln("                        <a href=\"/mnxt_gwzl/\" title=\"睾丸癌\">睾丸癌</a>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("            <li class=\"l2\">");
document.writeln("        		<dl>");
document.writeln("                	<dt>血液<br/>淋巴</dt>");
document.writeln("                    <dd>");
document.writeln("                        <a href=\"/xylb_bxb/\" title=\"白血病\">白血病</a>｜");
document.writeln("                        <a href=\"/xylb_lbl/\" title=\"淋巴瘤\" style='color:#ff0000;'>淋巴瘤</a>｜");
document.writeln("                        <a href=\"/xylb_hqjb/\" title=\"霍奇金淋巴瘤\">霍奇金淋巴瘤</a><br/>");
document.writeln("                        <a href=\"/xylb_fhqjlbl/\" title=\"非霍奇金淋巴瘤\">非霍奇金淋巴瘤</a>｜");
document.writeln("                        <a href=\"/xylb_btta/\" title=\"扁桃体癌\">扁桃体癌</a>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("            <li class=\"l3\">");
document.writeln("        		<dl>");
document.writeln("                	<dt>骨骼<br/>运动</dt>");
document.writeln("                    <dd>");
document.writeln("                        <a href=\"/qt_ga/\" title=\"骨癌\">骨癌</a>｜");
document.writeln("                        <a href=\"/qt_grl/\" title=\"骨肉瘤\">骨肉瘤</a><br/>");
document.writeln("                        <a href=\"/xylb_dfxgsa/\" title=\"多发性骨髓瘤\">多发性骨髓瘤</a>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("            <li class=\"l4\">");
document.writeln("        		<dl>");
document.writeln("                	<dt>其它<br/>肿瘤</dt>");
document.writeln("                    <dd>");
document.writeln("                        <a href=\"/qt_exhssl/\" title=\"黑色素瘤\" style='color:#ff0000;'>黑色素瘤</a>｜");
document.writeln("                        <a href=\"/qt_pfa/\" title=\"皮肤癌\">皮肤癌</a><br/>");
document.writeln("                        <a href=\"/qt_na/\" title=\"脑癌\">脑癌</a>｜");
document.writeln("                        <a href=\"/qt_rzzrl/\" title=\"软组织肉瘤\">软组织肉瘤</a>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("        </ul>");